config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :teams
  resources :statuses
  resources :projects
  resources :categories
  
  resources :tasks do 
    resources :historics
    collection do
      put :play_pause	
  	end
  end
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/historic.rb
class Historic < ApplicationRecord
  belongs_to :task
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :team
  has_many :tasks
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :status, optional: true
  belongs_to :project, optional: true
  belongs_to :user, optional: true
  has_many :historics
  # validates :user_id, presence: true
  validates :title, presence: true
  validates :category_id, presence: true
  validates :status_id, presence: true
  validates :project_id, presence: true
  validates :estimate_min, presence: true
  before_create :set_status
  before_create :set_user
  scope :opened, -> { where(status_id: Status.find_by(name:'aberta').id) }
  scope :closed, -> { where(status_id: Status.find_by(name:'entregue').id) }
  
  def playing?
  	return historics.any? ? historics.last.play : false
  end

  def set_status
    status_id = Status.find_by(name:'aberta').id
  end

  def change
  	if status.name == "aberta"
	   Historic.create(task_id: id, play: historics.any? ? !historics.last.play : true)
  	else 
  	  return false	  		
  	end
  end

  def get_prev_play(history)
    history = historics.where('id < ? AND play = ?', history.id, true).last
    return history
  end

  def worked_min
    min = 0.0
    if historics.any?
      # retorna tempo total já trabalhado
      historics.order('created_at asc').each do |history|   
        prev = get_prev_play(history)
        if prev.present?  
          time_diff  = history.created_at - prev.created_at
          range      = (time_diff / 1.minute).round
          min        = min + range
        end        
      end    
      if historics.last.play? 
        # time_diff  = DateTime.now - historics.last.created_at
        # range = (time_diff / 1.minute).round 
        # min = min + range 
      end
    end
    
    return min.round(2)
  
  end

  def codeId
    code = (id + 1000) * 47
    return "##{code}"
  end

  def set_user
    user_id = User.first.id
  end

  def percent 
    return (total_minutes.to_f / effort_min.to_f) * 100.0 
  end

end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users	
  has_many :projects
  has_many :users, through: :team_users
  has_many :tasks, through: :projects
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise  :database_authenticatable, 
          :registerable,
          :recoverable, 
          :rememberable, 
          :trackable, 
          :validatable,
          :omniauthable
  
  include DeviseTokenAuth::Concerns::User

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :play_pause, :update, :destroy]
  # before_action :autorize!

  # GET /tasks
  # GET /tasks.json
  def index
    # @tasks = @user.tasks.where(user_id: @user.id)
    @tasks = Task.opened
    if params[:status] && params[:status] == "closed"
      @tasks = Task.closed
    end
  end

  def closed
    @tasks = @user.where(user_id: @user.id).closed
  end

  def team 
    @tasks = @user.tasks.where.not(user_id: @user.id)
  end

  def play_pause
    respond_to do |format|
      if @task.change
        format.json { render :show, status: :ok, location: @task }
      else
        @task.errors.add(
          :status_id,  
          message: "A tarefa deve estar aberta"
        )
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.user_id = User.first.id
    @task.project_id = Project.first.id
    @task.category_id = Category.first.id
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = User.first.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity, location: "Não foi possível abrir a tarefa" }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def autorize!
      if !session[:session_user]
        redirect_to new_session_path 
      else 
        # session = Session.find_by(id: session[:session_user])
        @user = User.first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.fetch(:task, {}).permit(:title, :project_id, :category_id, :status_id, :user_id, :start_at, :estimate_at, :closed_at, :description, :priority, :estimate_min)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/historics_helper.rb
module HistoricsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_title %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id, id: :task_project_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :task_user_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id, id: :task_category_id %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.number_field :status_id, id: :task_status_id %>
  </div>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.datetime_select :start_at, id: :task_start_at %>
  </div>

  <div class="field">
    <%= form.label :estimate_at %>
    <%= form.datetime_select :estimate_at, id: :task_estimate_at %>
  </div>

   <div class="field">
    <%= form.label :estimate_min %>
    <%= form.number_field :estimate_min, id: :task_estimate_min %>
  </div>

  <div class="field">
    <%= form.label :closed_at %>
    <%= form.datetime_select :closed_at, id: :task_closed_at %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :task_description %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority, id: :task_priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Responsável</th>
      <th>Project</th>
      <th>Category</th>
      <th>Status</th>
      <th>Start at</th>
      <th>Estimate at</th>
      <th>Closed at</th>
      <th>Description</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.user_id %></td>
        <td><%= task.project_id %></td>
        <td><%= task.category_id %></td>
        <td><%= task.status_id %></td>
        <td><%= task.start_at %></td>
        <td><%= task.estimate_at %></td>
        <td><%= task.closed_at %></td>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @task.category_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status_id %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @task.start_at %>
</p>

<p>
  <strong>Estimate at:</strong>
  <%= @task.estimate_at %>
</p>

<p>
  <strong>Closed at:</strong>
  <%= @task.closed_at %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>