config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :teams
  resources :statuses
  resources :projects
  resources :categories
  
  resources :tasks do 
    resources :historics
    collection do
      put :play_pause	
  	end
  end
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/historic.rb
class Historic < ApplicationRecord
  belongs_to :task
end

app/controllers/historics_controller.rb
class HistoricsController < ApplicationController
  before_action :set_historic, only: [:show, :edit, :update, :destroy]

  # GET /historics
  # GET /historics.json
  def index
    @historics = Historic.all
  end

  # GET /historics/1
  # GET /historics/1.json
  def show
  end

  # GET /historics/new
  def new
    @historic = Historic.new
  end

  # GET /historics/1/edit
  def edit
  end

  # POST /historics
  # POST /historics.json
  def create
    @historic = Historic.new(historic_params)

    respond_to do |format|
      if @historic.save
        format.html { redirect_to @historic, notice: 'Historic was successfully created.' }
        format.json { render :show, status: :created, location: @historic }
      else
        format.html { render :new }
        format.json { render json: @historic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historics/1
  # PATCH/PUT /historics/1.json
  def update
    respond_to do |format|
      if @historic.update(historic_params)
        format.html { redirect_to @historic, notice: 'Historic was successfully updated.' }
        format.json { render :show, status: :ok, location: @historic }
      else
        format.html { render :edit }
        format.json { render json: @historic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historics/1
  # DELETE /historics/1.json
  def destroy
    @historic.destroy
    respond_to do |format|
      format.html { redirect_to historics_url, notice: 'Historic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historic
      @historic = Historic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historic_params
      params.require(:historic).permit(:task_id, :play)
    end
end

app/helpers/historics_helper.rb
module HistoricsHelper
end

app/views/historics/_form.html.erb
<%= form_with(model: historic, local: true) do |form| %>
  <% if historic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historic.errors.count, "error") %> prohibited this historic from being saved:</h2>

      <ul>
      <% historic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.number_field :task_id, id: :historic_task_id %>
  </div>

  <div class="field">
    <%= form.label :play %>
    <%= form.text_field :play, id: :historic_play %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/historics/edit.html.erb
<h1>Editing Historic</h1>

<%= render 'form', historic: @historic %>

<%= link_to 'Show', @historic %> |
<%= link_to 'Back', historics_path %>

app/views/historics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historics</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Play</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historics.each do |historic| %>
      <tr>
        <td><%= historic.task_id %></td>
        <td><%= historic.play %></td>
        <td><%= link_to 'Show', historic %></td>
        <td><%= link_to 'Edit', edit_historic_path(historic) %></td>
        <td><%= link_to 'Destroy', historic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historic', new_historic_path %>

app/views/historics/new.html.erb
<h1>New Historic</h1>

<%= render 'form', historic: @historic %>

<%= link_to 'Back', historics_path %>

app/views/historics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @historic.task_id %>
</p>

<p>
  <strong>Play:</strong>
  <%= @historic.play %>
</p>

<%= link_to 'Edit', edit_historic_path(@historic) %> |
<%= link_to 'Back', historics_path %>